### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by froggy974** [cyprieng/gazpar-home-assistant#22]
hi ,

since this month gazpar component sensor stay in error

```
This error originated from a custom integration.

Logger: custom_components.gazpar.sensor
Source: custom_components/gazpar/sensor.py:88
Integration: gazpar (documentation, issues)
First occurred: January 25, 2022, 16:01:31 (5 occurrences)
Last logged: 08:01:27

Failed to query Gazpar library with exception : Traceback (most recent call last): File "/config/custom_components/gazpar/sensor.py", line 76, in update_gazpar_data index_m3, index_kwh = gazpar.get_consumption() File "/config/custom_components/gazpar/gazpar.py", line 45, in f_retry return f(*args, **kwargs) File "/config/custom_components/gazpar/gazpar.py", line 88, in get_consumption index_m3 = response[self.pce]['releves'][-1]['indexFin'] IndexError: list index out of range
```

is it only on my side or something changed on grdf side ?

**Comment by froggy974** [comment]
sorry, it was coming from my side, my pce was removed from my grdf account
