### ISSUE TITLE
Requirements for gazpar not found: ['requests==2.25.1']

### ISSUE THREAD

**Issue by aardjoun** [cyprieng/gazpar-home-assistant#23]
Bonjour, 
Depuis quelques jours j'ai une erreur à l'installation de gazpar et au redémarrage de HA. 

Merci 

```Logger: homeassistant.core
Source: components/homeassistant/__init__.py:172 
First occurred: 13:38:19 (1 occurrences) 
Last logged: 13:38:19

Error executing service: <ServiceCall homeassistant.restart (c:7a4295d2fb3c4e61f4da9641129d024e)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1654, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 738, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 172, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.gazpar - Requirements for gazpar not found: ['requests==2.25.1']. ```

A l'installation :

```Logger: homeassistant.util.package
Source: util/package.py:99 
First occurred: 11:22:18 (6 occurrences) 
Last logged: 13:38:19

Unable to install package requests==2.25.1: warning: missing-index-doctype × The package index page being used does not have a proper HTML doctype declaration. ╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/armv7/ note: This is an issue with the page at the URL mentioned above. hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context. ERROR: Cannot install requests==2.25.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts ```

**Comment by aardjoun** [comment]
j'ai corrigé le souci en modifiant le manifest de requests==2.25.1 a requests>=2.25.1 car home assistant dans sa version actuelle embarque la version 2.27.1
